In [1]:
from nilearn import plotting
from nilearn.input_data import NiftiLabelsMasker

masker = NiftiLabelsMasker(labels_img="n/aal_SPM12/aal/ROI_MNI_V4.nii")
normal = masker.fit_transform("normal_data/IXI002-Guys-0828-T1.nii.gz")

/home/loganj/.local/lib/python3.9/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "


In [2]:
normal

array([[377.02526536, 393.65235046, 383.17804089, 400.2997002 ,
        103.83257544, 154.31628462, 349.72273728, 357.59987569,
        134.2387361 , 157.55924968, 335.69555302, 330.75126904,
        259.51033079, 275.90855223, 251.58016894, 300.23353014,
        368.46359029, 390.22700179, 387.67539038, 382.69593823,
        191.40363128, 192.35042354, 288.90011411, 277.43554919,
        178.55574356, 134.98232094, 112.29243192, 143.21703011,
        275.35774073, 290.60635625, 188.9063674 , 212.99373838,
        396.08172776, 397.81589909, 319.3595763 , 336.86065574,
        305.93388312, 295.09686334, 322.13383804, 340.54393993,
        250.16113161, 297.61227787, 237.67142774, 269.87759439,
        243.86322057, 259.85999064, 242.85662833, 250.47004925,
        210.42998641, 238.85110906, 211.78428778, 235.9701333 ,
        237.12370702, 176.21317413, 272.43314037, 283.56650763,
        357.25467949, 368.78128457, 300.89409056, 299.70253651,
        329.28690206, 345.9209034 , 295.

In [3]:
autistic = masker.fit_transform("DATA/50054/MP-RAGE/2000-01-01_00_00_00.0/I328862/ABIDE_50054_MRI_MP-RAGE_br_raw_20120830185721042_S164852_I328862.nii")

ValueError: File not found: 'DATA/50054/MP-RAGE/2000-01-01_00_00_00.0/I328862/ABIDE_50054_MRI_MP-RAGE_br_raw_20120830185721042_S164852_I328862.nii'

In [9]:
autistic

array([[ 56.10748443,  49.38183218,  81.4388755 ,  74.97267819,
        257.51035834, 236.33511252,  77.57805856,  73.72418783,
        200.53406408, 182.26770518, 124.10330169, 125.55508158,
        122.75723869, 106.02766637, 235.77055449, 203.8337891 ,
        191.62984945, 181.29830694,  66.9501358 ,  67.27299739,
        300.81677704, 295.54757282, 128.65820022, 124.99881657,
        204.96510125, 235.44271546, 249.72555889, 274.07741477,
        261.76199305, 259.0826156 , 208.61549546, 248.85269512,
        172.81966251, 195.29496495, 225.18033898, 253.89464741,
        309.30084086, 324.35674069, 320.77491866, 312.84657948,
        309.14074074, 303.515625  , 215.07491208, 237.28878072,
        134.07920698, 141.26897959, 292.29331877, 284.96248251,
         92.23140156, 102.12307844, 126.79431431, 129.71554252,
        177.37827654, 174.7387483 , 283.15518312, 291.23660765,
         48.62393641,  48.46334144,  32.2403954 ,  23.50918618,
         53.3926557 ,  50.67606587,  72.

In [11]:
normal2 = masker.fit_transform("normal_data/IXI016-Guys-0697-T1.nii.gz")
normal2

array([[ 875.89974044,  977.3484766 ,  906.97026593,  954.89111233,
         545.58555516,  549.27256835,  900.16340242,  915.38168852,
         560.76889065,  742.2958415 ,  835.77601507,  907.66706152,
         835.45988287,  821.67052483,  949.76721507,  939.41829937,
         953.24195557, 1043.84242641,  747.23405044,  772.56274331,
         858.56112979,  978.00395807,  667.38362956,  735.58883717,
         474.43330301,  425.06524415,  483.94475754,  522.27315437,
         779.64135265,  785.43383495,  408.61084163,  394.62245124,
         855.75541427,  791.92352384,  929.06560991,  757.76026513,
         744.75834478,  901.59874725,  936.14479446,  937.37725963,
         796.56210946,  713.88301405,  747.6650716 ,  768.75850657,
         738.83575132,  697.52368078,  722.94169102,  687.54373456,
         660.15332634,  726.9591271 ,  599.17125869,  703.05930754,
         552.60483883,  679.60425996,  786.47512674,  866.60025387,
         843.97486547, 1022.8616369 ,  801.42171

In [16]:
import numpy as np

In [14]:
# normal brains positive corr.
np.corrcoef(normal, normal2)

array([[1.        , 0.63116625],
       [0.63116625, 1.        ]])

In [15]:
np.corrcoef(normal, autistic)

array([[ 1.        , -0.25327699],
       [-0.25327699,  1.        ]])

In [18]:
# neg. corr between normal and autsitc brains
np.corrcoef(normal2, autistic)

array([[ 1.        , -0.13740058],
       [-0.13740058,  1.        ]])

In [19]:
autistic2 = masker.fit_transform("DATA/50110/MP-RAGE/2000-01-01_00_00_00.0/I329408/ABIDE_50110_MRI_MP-RAGE_br_raw_20120830233415615_S165398_I329408.nii")
autistic2

array([[159.83182647,  81.22625473, 188.82879108, 150.44824947,
        325.16429127, 274.80633007, 197.54890969, 153.74510188,
        318.74894098, 207.57721675, 224.41088632, 165.94296442,
        249.01858442, 175.5274291 , 273.03961567, 215.93144156,
        284.91414141, 190.42158152, 148.85595424, 142.94324136,
        317.33214286, 339.06574394, 168.23383189, 208.14597001,
        235.52729485, 305.96827485, 281.37470657, 314.71208054,
        340.55447078, 252.89915254, 247.16223214, 293.25380807,
        170.05744462, 215.17894079, 234.01592873, 262.0108209 ,
        359.49959775, 298.85963521, 351.77276205, 339.58618785,
        381.68197279, 299.29133065, 213.07650576, 229.17376411,
        159.53722186, 171.62471416, 241.65189949, 273.60517129,
        116.38906164, 134.12690265, 203.08600628, 152.30618446,
        244.11975013, 195.73887765, 314.24859216, 270.11313542,
        157.76106913,  77.56287957,  68.0783046 ,  22.50873094,
        171.16234164,  71.54042   , 210.

In [20]:
# seems brains of the same type have positive corr.
np.corrcoef(autistic, autistic2)

array([[1.        , 0.87109042],
       [0.87109042, 1.        ]])

In [21]:
from sklearn.svm import SVC

clf = SVC(gamma="auto")

In [22]:
import os

normal_paths = ["normal_data/" + x for x in os.listdir("normal_data/")]

In [59]:
normal_brains = [masker.fit_transform(x)[0] for x in normal_paths]

In [26]:
len(normal_brains)

18

In [27]:
autistic_paths = ["autistic_data/" + x for x in os.listdir("autistic_data/")]

In [29]:
autistic_paths

['autistic_data/ABIDE_50646_MRI_MP-RAGE_br_raw_20120830182459544_S164765_I328775.nii',
 'autistic_data/ABIDE_50167_MRI_MP-RAGE_br_raw_20120831140522566_S165708_I329754.nii',
 'autistic_data/ABIDE_50125_MRI_MP-RAGE_br_raw_20120830174129152_S164649_I328659.nii',
 'autistic_data/ABIDE_50122_MRI_MP-RAGE_br_raw_20120830213955992_S165183_I329193.nii',
 'autistic_data/ABIDE_50405_MRI_MP-RAGE_br_raw_20120830183350015_S164788_I328798.nii',
 'autistic_data/ABIDE_50136_MRI_MP-RAGE_br_raw_20120830202014457_S165053_I329063.nii',
 'autistic_data/ABIDE_50246_MRI_MP-RAGE_br_raw_20120905094204756_S166107_I330286.nii',
 'autistic_data/ABIDE_50355_MRI_MP-RAGE_br_raw_20120830192044297_S164918_I328928.nii',
 'autistic_data/ABIDE_50602_MRI_MP-RAGE_br_raw_20120830190108410_S164863_I328873.nii',
 'autistic_data/ABIDE_50106_MRI_MP-RAGE_br_raw_20120830215147324_S165204_I329214.nii',
 'autistic_data/ABIDE_50124_MRI_MP-RAGE_br_raw_20120830220922858_S165240_I329250.nii',
 'autistic_data/ABIDE_50166_MRI_MP-RAGE_br_

In [57]:
autistic_brains = [masker.fit_transform(x)[0] for x in autistic_paths]

In [58]:
[x.shape for x in autistic_brains]

[(116,),
 (116,),
 (116,),
 (116,),
 (116,),
 (116,),
 (116,),
 (22,),
 (116,),
 (116,),
 (116,),
 (116,),
 (116,),
 (116,),
 (116,),
 (22,),
 (116,),
 (116,),
 (22,),
 (116,),
 (116,),
 (22,),
 (22,),
 (116,),
 (116,),
 (116,),
 (22,),
 (22,),
 (115,),
 (116,),
 (22,),
 (22,),
 (116,),
 (22,),
 (116,),
 (22,),
 (116,),
 (116,),
 (116,),
 (116,),
 (116,)]

In [62]:
# only volume data
autistic_brains = [x for x in filter(lambda x: x.shape != (1, 22), autistic_brains)]

In [41]:
len(autistic_brains)

30

In [64]:
len(autistic_brains[12:])

29

In [67]:
from sklearn.model_selection import train_test_split
import pandas as pd

X_train, X_test, y_train, y_test = train_test_split(pd.Series(autistic_brains[23:]), pd.Series(normal_brains), test_size=0.1)

In [68]:
X_train

7     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0     [84.09837707038258, 74.75113237099437, 137.270...
10    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
11    [169.75044323097651, 193.31576418406948, 184.6...
3     [0.0, 0.0, 0.0, 0.0, 0.016519488428745434, 0.0...
8     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
6     [159.83182647014132, 81.22625473294127, 188.82...
5     [18.862421929215824, 222.40372670807454, 5.413...
9     [1147.9740853658536, 1676.5977151730258, 1451....
12    [0.0, 0.0, 0.6628980299838929, 0.0, 0.06836175...
14    [130.37561598184848, 107.0575409290809, 151.73...
1     [268.89421440726034, 300.98365868086364, 179.1...
15    [27.143901453957998, 229.31876663708962, 19.52...
2     [148.9786562666194, 134.96969136943264, 198.48...
16    [0.30408542246982356, 144.45149364093464, 0.17...
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
dtype: object

In [69]:
clf.fit(X_train, y_train)

ValueError: setting an array element with a sequence.